export type WorkspaceImprovementPage = {
  id: string
  label: string
  route: string
  match: (path: string) => boolean
  recommendations: Array<string>
}

export const WORKSPACE_IMPROVEMENT_PAGES: Array<WorkspaceImprovementPage> = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    route: '/dashboard',
    match: (path) => path === '/dashboard',
    recommendations: [
      'Custom KPI pinning',
      'Drag-reorder widgets',
      'Daily summary strip',
      'Failing-system heatmap',
      'Recent automation timeline',
      'Mobile compact cards',
      'Saved dashboard layouts',
      'Anomaly callouts',
      'Source freshness badges',
      'Quick command launcher',
      'Goal progress row',
      'Model spend sparkline',
      'Inbox/action queue tiles',
      'Deploy health tile',
      'Personal focus block',
      'Workspace diff summary',
      'System restart history',
      'What changed today panel',
      'Cross-page alerts',
      'Printable executive view',
    ],
  },
  {
    id: 'phone',
    label: 'Phone Cockpit',
    route: '/phone',
    match: (path) => path.startsWith('/phone'),
    recommendations: [
      'Mobile-first briefing header',
      'One-thumb capture composer',
      'Offline capture queue',
      'Notification permission diagnostics',
      'Shortcut install checklist',
      'Next meeting quick actions',
      'Urgent mail triage strip',
      'Task capture templates',
      'Presence-aware prompt timing',
      'Local notification history',
      'PWA update banner',
      'Voice handoff to LILY',
      'Calendar conflict warnings',
      'Apple Focus mode hints',
      'Home-screen safe-area polish',
      'Low-connectivity fallback',
      'Quick reply draft staging',
      'Daily phone digest',
      'Device bridge health badge',
      'Send-to-workspace action rail',
    ],
  },
  {
    id: 'lily',
    label: 'LILY',
    route: '/lily',
    match: (path) => path.startsWith('/lily'),
    recommendations: [
      'Voice readiness checklist',
      'Microphone diagnostics',
      'Last conversation recap',
      'Push-to-talk mobile mode',
      'Transcript search',
      'Suggested follow-ups',
      'Voice latency meter',
      'Fallback transport indicator',
      'Persona controls',
      'Wake-word status',
      'Session bookmarks',
      'Conversation export',
      'Noise calibration',
      'LiveKit health panel',
      'Interruption handling',
      'Mobile one-hand controls',
      'Recent commands',
      'Action extraction',
      'Voice quality score',
      'Safe-mode toggle',
    ],
  },
  {
    id: 'chat',
    label: 'Chat',
    route: '/chat/main',
    match: (path) =>
      path === '/' || path === '/new' || path.startsWith('/chat'),
    recommendations: [
      'Better thread search',
      'Pinned sessions',
      'Model comparison mode',
      'Tool-call timeline',
      'Continue-from-here checkpoints',
      'Attachment tray',
      'Mobile swipe between sessions',
      'Reply draft mode',
      'Cost-per-thread badge',
      'Failed tool retry button',
      'Branch/task context chips',
      'Inline artifact viewer',
      'Conversation health indicators',
      'Saved prompt snippets',
      'Message version compare',
      'Session archive workflow',
      'Local file reference picker',
      'Command palette integration',
      'Streaming quality diagnostics',
      'Handoff to workspace page actions',
    ],
  },
  {
    id: 'playground',
    label: 'HermesWorld',
    route: '/playground',
    match: (path) => path.startsWith('/playground'),
    recommendations: [
      'Mobile control tuning',
      'Minimap',
      'Agent NPC status bubbles',
      'Quest log tied to real tasks',
      'Performance mode toggle',
      'Lower-end device fallback',
      'Guided onboarding path',
      'Object interaction hints',
      'Scene screenshot capture',
      'Agent meeting room',
      'World event timeline',
      'Keyboard remap UI',
      'Touch joystick calibration',
      'Ambient status overlays',
      'Achievement hooks',
      'Workspace portals',
      'Real automation quests',
      'Accessibility contrast mode',
      'Asset preloader status',
      'Save/resume position',
    ],
  },
  {
    id: 'files',
    label: 'Files',
    route: '/files',
    match: (path) => path.startsWith('/files'),
    recommendations: [
      'Persist search/filter state',
      'File type chips on visible route',
      'Recent files',
      'Favorite folders',
      'Mobile preview drawer',
      'Diff-before-save in visible route',
      'Bulk upload progress',
      'Image grid mode',
      'Markdown outline',
      'Copy reference button per file',
      'Rename validation',
      'Conflict detection',
      'File activity log',
      'Generated-files filter',
      'Hidden-files toggle',
      'Path breadcrumbs on mobile',
      'Keyboard shortcuts',
      'Safe delete undo',
      'Download folder zip',
      'Open in related page actions',
    ],
  },
  {
    id: 'terminal',
    label: 'Terminal',
    route: '/terminal',
    match: (path) => path.startsWith('/terminal'),
    recommendations: [
      'Saved command snippets',
      'Mobile command palette',
      'Session labels',
      'Running-process chips',
      'Copy last command/output',
      'Shell health indicator',
      'Reconnect banner',
      'Command history search',
      'Workspace cwd selector',
      'Split terminal panes',
      'Long-running command monitor',
      'Exit-code badges',
      'Safe command warnings',
      'Terminal transcript export',
      'Environment summary drawer',
      'Mobile input macros',
      'Tmux session switcher',
      'Auto-scroll lock',
      'ANSI theme picker',
      'Command-to-task conversion',
    ],
  },
  {
    id: 'jobs',
    label: 'Jobs',
    route: '/jobs',
    match: (path) => path.startsWith('/jobs'),
    recommendations: [
      'Job dependency graph',
      'Retry failed job button',
      'SLA badges',
      'Next run countdowns',
      'Job owner labels',
      'Mobile status cards',
      'Failure clustering',
      'Job log search',
      'Schedule editor',
      'Pause/resume controls',
      'Run history charts',
      'Alert routing',
      'Dry-run mode',
      'Impact labels',
      'Duplicate job detector',
      'Stale job warnings',
      'Output artifact links',
      'Rerun with same args',
      'Cron explain text',
      'Automation health score',
    ],
  },
  {
    id: 'tasks',
    label: 'Tasks',
    route: '/tasks',
    match: (path) => path.startsWith('/tasks'),
    recommendations: [
      'Kanban/list toggle',
      'Due-date quick filters',
      'Priority lanes',
      'Task source badges',
      'Mobile swipe complete',
      'Recurring task support',
      'Blocked/waiting state',
      'Task-to-chat context',
      'Calendar grouping',
      'Owner assignment',
      'Batch edit',
      'Aging indicators',
      'Task import from email/chat',
      'Focus mode',
      'Related files links',
      'Automation-created labels',
      'Done archive',
      'Dependency links',
      'Effort estimate',
      'Daily task digest',
    ],
  },
  {
    id: '75-tracker',
    label: '75 Hard/Soft',
    route: '/75-tracker',
    match: (path) => path.startsWith('/75-tracker'),
    recommendations: [
      'Program selector',
      'Streak calendar',
      'Missed-day recovery notes',
      'Photo upload',
      'Water tracker',
      'Workout split logging',
      'Reading timer',
      'Diet compliance notes',
      'Mobile check-off widget',
      'Progress rings',
      'Soft/hard comparison',
      'Habit reminders',
      'Weekly trend view',
      'Export summary',
      'Start-date reset',
      'Accountability notes',
      'Apple Health hooks',
      'Violation reason tracking',
      'Milestone badges',
      'Dashboard mini tile',
    ],
  },
  {
    id: 'conductor',
    label: 'Conductor',
    route: '/conductor',
    match: (path) => path.startsWith('/conductor'),
    recommendations: [
      'Runbook library',
      'Orchestration graph',
      'Approval gates',
      'Dry-run preview',
      'Agent assignment matrix',
      'Mobile command cards',
      'Execution timeline',
      'Rollback plan viewer',
      'Input validation',
      'Cost estimate',
      'Prompt templates',
      'Queue prioritization',
      'Stuck-step detector',
      'Live logs',
      'Handoff summary',
      'Saved workflows',
      'Dependency checks',
      'Post-run report',
      'Reusable variables',
      'One-click incident workflow',
    ],
  },
  {
    id: 'operations',
    label: 'Operations',
    route: '/operations',
    match: (path) => path.startsWith('/operations'),
    recommendations: [
      'Operations command center',
      'Queue triage',
      'Incident severity matrix',
      'Owner routing',
      'Aging alerts',
      'Mobile action tray',
      'SOP links',
      'Recent decisions',
      'Customer/system filters',
      'Escalation timers',
      'Evidence attachment panel',
      'Automation suggestions',
      'Completion metrics',
      'Exception board',
      'Dependency map',
      'Daily ops brief',
      'Risk register',
      'Approvals inbox',
      'Audit log',
      'Next best action strip',
    ],
  },
  {
    id: 'ops-intelligence',
    label: 'Ops Intelligence',
    route: '/ops-intelligence',
    match: (path) => path.startsWith('/ops-intelligence'),
    recommendations: [
      'Correlation timeline',
      'Trend anomalies',
      'Root-cause clustering',
      'Signal confidence score',
      'Source freshness',
      'Mobile executive summary',
      'Incident prediction',
      'Top recurring issues',
      'Automation ROI',
      'Unresolved risk panel',
      'Graph view',
      'Weekly trend export',
      'Signal noise filters',
      'Remediation suggestions',
      'Cost impact estimate',
      'Live data coverage',
      'Stale data alerts',
      'Saved investigations',
      'Cross-system entity page',
      'Narrative report builder',
    ],
  },
  {
    id: 'swarm',
    label: 'Swarm',
    route: '/swarm',
    match: (path) => path === '/swarm' || path.startsWith('/swarm2'),
    recommendations: [
      'Worker health score',
      'Stale runtime drilldown',
      'Live terminal preview',
      'Assignment board',
      'Agent capability matrix',
      'Mobile worker cards',
      'Failed handoff alerts',
      'Task queue per worker',
      'Runtime restart action',
      'Output freshness chart',
      'Model/provider labels',
      'Cost by worker',
      'Stuck-agent detector',
      'Swarm timeline',
      'Role templates',
      'Compare worker performance',
      'Summon agent action',
      'Artifact links',
      'Heartbeat logs',
      'Safety limits panel',
    ],
  },
  {
    id: 'memory',
    label: 'Memory',
    route: '/memory',
    match: (path) => path.startsWith('/memory'),
    recommendations: [
      'Memory freshness score',
      'Duplicate memory detector',
      'Source citations',
      'Search filters',
      'Graph relationship view',
      'Mobile memory cards',
      'Stale memory review queue',
      'Pin key memories',
      'Memory diff history',
      'Confidence labels',
      'User correction inbox',
      'Import/export',
      'Workspace-specific memory filter',
      'Privacy controls',
      'Auto-summarize clusters',
      'Memory provenance',
      'Forgotten-item audit',
      'Recall test mode',
      'Semantic search tuning',
      'Promote to durable workflow',
    ],
  },
  {
    id: 'skills',
    label: 'Skills',
    route: '/skills',
    match: (path) => path.startsWith('/skills'),
    recommendations: [
      'Skill health checks',
      'Usage analytics',
      'Install/update status',
      'Broken skill detector',
      'Mobile skill launcher',
      'Skill dependency graph',
      'Skill version pinning',
      'Examples preview',
      'Skill test runner',
      'Duplicate skill finder',
      'Recommended skills',
      'Local/custom badges',
      'Permission summary',
      'Last-used timestamps',
      'Failure history',
      'Skill docs viewer',
      'Enable/disable toggle',
      'Marketplace compare',
      'Skill authoring wizard',
      'Export skill bundle',
    ],
  },
  {
    id: 'mcp',
    label: 'MCP',
    route: '/mcp',
    match: (path) => path.startsWith('/mcp'),
    recommendations: [
      'Server health matrix',
      'Tool latency chart',
      'Failed tool-call history',
      'Auth status per server',
      'Mobile server cards',
      'Restart server action',
      'Schema diff viewer',
      'Install wizard',
      'Capability search',
      'Permission warnings',
      'Stale server detector',
      'Config validation',
      'Logs per server',
      'Tool usage analytics',
      'Sandbox labels',
      'Duplicate tool detection',
      'Dependency status',
      'Environment variable checker',
      'Connector marketplace',
      'One-click diagnostic bundle',
    ],
  },
  {
    id: 'profiles',
    label: 'Profiles',
    route: '/profiles',
    match: (path) => path.startsWith('/profiles'),
    recommendations: [
      'Profile comparison',
      'Active profile badge',
      'Model/provider defaults',
      'Permission presets',
      'Mobile profile switcher',
      'Profile history',
      'Role descriptions',
      'Recommended profile per task',
      'Import/export',
      'Profile health check',
      'Secret coverage',
      'Tool access matrix',
      'Prompt preview',
      'Fallback profile',
      'Cost policy',
      'Profile-specific memory',
      'Workspace binding',
      'Audit trail',
      'Clone profile action',
      'Conflict warnings',
    ],
  },
  {
    id: 'meetings',
    label: 'Meetings',
    route: '/meetings',
    match: (path) => path.startsWith('/meetings'),
    recommendations: [
      'Upcoming meeting queue',
      'Prep brief generator',
      'Transcript import status',
      'Action extraction',
      'Attendee context',
      'Mobile meeting cards',
      'Follow-up draft',
      'To Do sync health',
      'Agenda templates',
      'Decision log',
      'Stale action alerts',
      'Calendar integration health',
      'Meeting quality score',
      'Related files',
      'Recurring meeting memory',
      'Export to notes',
      'Owner assignment',
      'Due date extraction',
      'Meeting timeline',
      'Unresolved question list',
    ],
  },
  {
    id: 'presence',
    label: 'Presence',
    route: '/presence',
    match: (path) => path.startsWith('/presence'),
    recommendations: [
      'Current availability card',
      'Teams/Slack status sync',
      'Focus-mode schedule',
      'Manual override',
      'Mobile quick status',
      'Availability history',
      'Stale presence warning',
      'Calendar-aware presence',
      'Notification routing',
      'Presence confidence',
      'Status source badges',
      'Quiet-hours controls',
      'Team dashboard',
      'Automation pause rules',
      'Meeting conflict alerts',
      'Travel/offline mode',
      'Status webhook',
      'Presence analytics',
      'Contact priority rules',
      'Do-not-interrupt explanation',
    ],
  },
  {
    id: 'it-ops',
    label: 'ConnectWise',
    route: '/it-ops',
    match: (path) => path.startsWith('/it-ops'),
    recommendations: [
      'Ticket queue heatmap',
      'Approval status audit',
      'SLA countdowns',
      'Requester context',
      'Mobile ticket triage',
      'Board/subtype filters',
      'Native workflow validation',
      'Stuck approval detector',
      'AI policy checkbox audit',
      'Ticket aging bands',
      'Duplicate ticket clustering',
      'Escalation suggestions',
      'Portal form diagnostics',
      'Live PSA sync status',
      'Technician workload',
      'Customer impact score',
      'Resolution templates',
      'Audit evidence links',
      'Cancelled/approved queue cleanup',
      'Verify-in-portal checklist',
    ],
  },
  {
    id: 'barry',
    label: 'Barry',
    route: '/barry',
    match: (path) => path.startsWith('/barry'),
    recommendations: [
      'Conversation memory panel',
      'Recent legal/workflow topics',
      'Draft review mode',
      'Source citation checks',
      'Mobile chat polish',
      'Persona boundaries',
      'Action extraction',
      'Document upload',
      'Follow-up reminders',
      'Risk labels',
      'Matter/project grouping',
      'Template library',
      'Conversation export',
      'Pending question list',
      'Confidence scoring',
      'Compare answer versions',
      'Quick facts drawer',
      'Safe disclaimer policy',
      'Handoff to Tasks',
      'Review queue',
    ],
  },
  {
    id: 'settings',
    label: 'Settings',
    route: '/settings',
    match: (path) => path.startsWith('/settings'),
    recommendations: [
      'Global search persistence',
      'Changed-settings summary',
      'Reset section button',
      'Mobile section drawer',
      'Config export',
      'Validation warnings',
      'Secret status panel',
      'Theme preview grid',
      'Keyboard shortcut editor',
      'Model/provider test button',
      'Profile-linked settings',
      'Feature flag panel',
      'Accessibility controls',
      'Notification test',
      'Connection diagnostics',
      'Settings audit log',
      'Dangerous settings confirmation',
      'Import settings',
      'Environment variable viewer',
      'Recommended configuration assistant',
    ],
  },
]

export function findWorkspaceImprovementPage(pathname: string) {
  return (
    WORKSPACE_IMPROVEMENT_PAGES.find((page) => page.match(pathname)) ?? null
  )
}

export function countWorkspaceRecommendations() {
  return WORKSPACE_IMPROVEMENT_PAGES.reduce(
    (count, page) => count + page.recommendations.length,
    0,
  )
}
