export type WorkspaceImprovementPage = {
  id: string
  label: string
  route: string
  match: (path: string) => boolean
  recommendations: Array<string>
}

export const WORKSPACE_IMPROVEMENT_SOURCE =
  'docs/hermes-workspace-look-code-review-2026-05-27.md'

export const WORKSPACE_IMPROVEMENT_PAGES: Array<WorkspaceImprovementPage> = [
  {
    id: "dashboard",
    label: "Dashboard",
    route: "/dashboard",
    match: (path) => path === '/dashboard',
    recommendations: [
      "Move the update toast out of the top center of the dashboard; it obscures the most important first-viewport status.",
      "Promote \"Gateway data stale\" to a stronger incident banner with one primary recovery action.",
      "Replace the separate severity-color legend with inline severity chips on the items that need interpretation.",
      "Collapse the \"Dashboard Control Plane\" card into a slimmer command bar above the dashboard cards.",
      "Add a visible H2 for the main dashboard section so screen readers and DOM snapshots expose structure.",
      "Reduce the number of simultaneous card borders in the first viewport; the page reads as a grid of boxes before it reads as priorities.",
      "Add a \"today only\" mobile digest that hides lower-priority analytics until expanded.",
      "Make \"Waiting on others\" clickable into the exact tasks or sessions that created the count.",
      "Replace \"Overview refreshed never\" with a timestamp plus source name and recovery hint.",
      "Add a dashboard data freshness hook shared with Phone Cockpit so stale labels stay consistent.",
      "Split `dashboard-screen.tsx` into query, control-plane, daily-loop, analytics, and layout modules.",
      "Add tests for the \"stale gateway\" and \"no recent workstream\" action ranking.",
      "Persist daily-loop checklist state through the same typed storage helper used by Tasks.",
      "Add keyboard shortcuts for refresh, open tasks, and copy status brief.",
      "Make hidden-widget recovery available in the main UI instead of only inside edit mode.",
      "Add a compact \"next action\" card that is visually dominant on desktop and mobile.",
      "Convert repeated metric cards to a single metric-card primitive with typed variants.",
      "Add loading skeletons for dashboard source refresh instead of swapping directly from stale to loaded text.",
      "Add a dashboard diagnostics export that includes source freshness and user-hidden widgets.",
      "Keep the dashboard as the default command center, but route deep operational work into the specialized pages faster.",
    ],
  },
  {
    id: "phone",
    label: "Phone Cockpit",
    route: "/phone",
    match: (path) => path.startsWith('/phone'),
    recommendations: [
      "Move the update toast below the mobile header or into a slim inline strip; it covers the urgent-task headline.",
      "Remove the duplicate first-viewport \"Loading...\" H1 state from the rendered DOM after data is ready.",
      "Make \"4 urgent tasks\" tappable into a filtered task queue with one-tap completion and snooze.",
      "Add a low-data mode preview of what will be hidden before the user toggles it.",
      "Add a safe-area spacer above the bottom nav so pinned low-data actions are not clipped.",
      "Convert \"Desk state stale\" into a button that explains the stale source and refresh path.",
      "Add a single thumb-zone primary action for \"Capture\" that stays above the bottom navigation.",
      "Put \"Next meeting\" and \"Waiting\" into one timeline strip so the page feels glanceable.",
      "Add a \"driving/walking\" ultra-compact mode with only urgent count, next event, capture, and LILY mic.",
      "Add haptic feedback to the pinned action buttons, matching the mobile menu behavior.",
      "Split `phone-cockpit-screen.tsx` into summary hooks, card components, local queue, and mobile layout modules.",
      "Move localStorage queue, pinned cards, and collapsed cards behind a typed persistence helper.",
      "Add tests for offline capture replay and stale-source display.",
      "Add a visible sync state for pending local captures so offline input is not ambiguous.",
      "Add a \"last opened\" recency signal for daily usage habit formation.",
      "Make card collapse/pin controls icon-only with labels in accessible names to reduce text density.",
      "Add a one-tap \"done for now\" state that summarizes what remains instead of making the user inspect every card.",
      "Keep the tab rail, but shorten the labels when the viewport is narrow.",
      "Add a mobile screenshot test that asserts the update toast does not overlap the H1.",
      "Share source-health logic with Dashboard, Meetings, Presence, and IT Ops.",
    ],
  },
  {
    id: "lily",
    label: "LILY",
    route: "/lily",
    match: (path) => path.startsWith('/lily'),
    recommendations: [
      "Move voice setup diagnostics into a progressive checklist with the current blocker highlighted first.",
      "Add a stronger \"typed fallback active\" state so failed voice setup still feels productive.",
      "Give the transcript timeline a fixed height with virtualization for long sessions.",
      "Add a top-level \"voice ready / degraded / unavailable\" badge to the first viewport.",
      "Make microphone permission state actionable with browser-specific copy and a retry path.",
      "Add a mobile sticky mic control that avoids bottom-nav overlap.",
      "Split the 1,900-line route into voice state, LiveKit token, typed chat, diagnostics, and transcript components.",
      "Extract browser support detection into a shared tested module instead of keeping it near route UI.",
      "Add tests for permission denied, token expired, worker offline, and typed fallback handoff.",
      "Add a \"copy voice diagnostics\" button that redacts token and device identifiers.",
      "Add a first-run setup card that only appears when a required voice dependency is missing.",
      "Keep \"Start LILY\" as the primary action, but disable it with a clear reason when prerequisites fail.",
      "Add latency and last-heard indicators for the voice loop.",
      "Add clear reconnect behavior after network loss instead of relying on page reload.",
      "Use the same settings route-link pattern as Settings for model, voice, and notification setup.",
      "Add a compact mobile state that shows only mic, transcript last line, and typed fallback.",
      "Move LiveKit error normalization into a utility with unit tests.",
      "Add an accessibility pass for live transcript announcements.",
      "Add an end-of-session summary handoff to Tasks or Chat.",
      "Add a LILY-specific visual smoke assertion that the mic control is visible on mobile.",
    ],
  },
  {
    id: "chat",
    label: "Chat",
    route: "/chat/main",
    match: (path) => path === '/' || path === '/new' || path.startsWith('/chat'),
    recommendations: [
      "Add a real H1 or visually hidden page title for Chat; the DOM snapshot currently has no H1.",
      "Move the update toast away from the chat status strip; it competes with model/session state.",
      "Reduce the top diagnostics panel height when the chat is empty so the composer feels closer to the center task.",
      "Make \"Begin a session\" the only dominant empty-state headline and demote secondary tool chips.",
      "Add a first-run command rail that is hidden after the first successful message.",
      "Add a one-click \"resume latest with context\" action that explains what context will be restored.",
      "Keep the composer sticky, but reserve bottom-right space so diagnostics and floating buttons do not collide.",
      "Split `chat-screen.tsx` into session lifecycle, composer state, message streaming, layout, and command handlers.",
      "Move sessionStorage recovery behavior into a typed hook with tests for stale waiting state.",
      "Revisit the TODO in `use-realtime-chat-history.ts` and either remove it or add a tracked follow-up test.",
      "Virtualize long message lists and artifact previews to protect mobile memory.",
      "Add a route-level diagnostic bundle for active session, model, provider, tools, and recovery state.",
      "Add a \"safe mutation gate\" affordance that clearly shows why a risky action is blocked.",
      "Make the profile selector more prominent when the selected profile changes tool availability.",
      "Add visual distinction between local-only drafts, sent messages, and backend-confirmed messages.",
      "Convert repeated status chips into a shared compact status component.",
      "Add keyboard shortcut discovery inside command palette instead of inline text in the main surface.",
      "Add tests for empty-state command chips, resume latest, and failed send recovery.",
      "Add a mobile composer mode that starts with capture first and expands to full tools on demand.",
      "Add page-level performance budget checks because Chat is one of the highest-control-count pages.",
    ],
  },
  {
    id: "playground",
    label: "HermesWorld",
    route: "/playground",
    match: (path) => path.startsWith('/playground'),
    recommendations: [
      "Add a real H1 or visually hidden page title; the route currently has no H1 in the DOM snapshot.",
      "Keep the launch checklist, but make the primary \"enter world\" action visually dominant.",
      "Add a WebGL capability preflight before loading expensive 3D assets.",
      "Add a reduced-motion and low-GPU mode for daily mobile usage.",
      "Add a loading progress indicator for GLB and texture assets.",
      "Add an escape hatch when the 3D scene fails instead of only logging render failure.",
      "Split large playground state into world, RPG, multiplayer, settings, and narration modules.",
      "Add smoke assertions that the canvas has nonblank pixels after scene load.",
      "Add mobile-safe HUD placement that cannot collide with bottom navigation.",
      "Add a \"daily reward / next quest\" summary for quick non-game use.",
      "Add persistent but resettable character customization state with schema versioning.",
      "Move admin/owner localStorage clearing into a named security helper.",
      "Add accessibility alternatives for key game actions outside the canvas.",
      "Add a diagnostics panel for FPS, connection state, asset load, and input mode.",
      "Add tests around settings persistence and photosensitive warning behavior.",
      "Add route-specific bundle budget monitoring because this page can dominate load cost.",
      "Make \"open full\" copy more specific to the action it performs.",
      "Add a mobile landscape orientation recommendation only when the device is narrow.",
      "Keep game visuals richer than operations pages, but reduce nonessential panel borders.",
      "Add a graceful fallback to a 2D map or journal if 3D cannot initialize.",
    ],
  },
  {
    id: "files",
    label: "Files",
    route: "/files",
    match: (path) => path.startsWith('/files'),
    recommendations: [
      "Add a real H1 or visually hidden page title; the visible page currently exposes no H1.",
      "Replace route-level reload fallback with a shared route error component and retry action.",
      "Make current workspace/path the strongest first-viewport signal.",
      "Add a breadcrumb that remains sticky while browsing deep folders.",
      "Add file operation status for copy, move, rename, delete, and upload.",
      "Add a diff-preview affordance before destructive edits or overwrites.",
      "Split the 2,100-line screen into browser, preview, operations, recent changes, and API hooks.",
      "Add tests for path traversal protection from the UI, not just API behavior.",
      "Add keyboard navigation for file list, preview pane, and action menu.",
      "Add file-type icons that are consistent with the rest of the workspace icon system.",
      "Add mobile file actions as a bottom sheet instead of dense inline controls.",
      "Add a \"recently touched by agent\" filter for Tyler's workflow.",
      "Add a \"pin workspace root\" control for common folders.",
      "Add preview loading skeletons to avoid blank pane ambiguity.",
      "Add search result highlighting inside the file browser.",
      "Add a diagnostic bundle for current path, root, last API error, and selected file.",
      "Add clearer disabled states when an operation is unavailable.",
      "Add an undo window for local rename/delete operations when possible.",
      "Add visual smoke coverage for preview pane open state.",
      "Reduce card count in the first viewport so the file list reads as the main object.",
    ],
  },
  {
    id: "terminal",
    label: "Terminal",
    route: "/terminal",
    match: (path) => path.startsWith('/terminal'),
    recommendations: [
      "Add a real H1 or visually hidden title for Terminal.",
      "Replace route-level reload fallback with shared route recovery UI.",
      "Keep the terminal surface visually dominant; move secondary controls into a compact toolbar.",
      "Add explicit session state: connected, reconnecting, detached, failed, and read-only.",
      "Add a mobile-first command palette for common safe commands.",
      "Add a clear \"dangerous command\" interlock before destructive shell actions.",
      "Split `terminal-workspace.tsx` into transport, tabs, xterm adapter, toolbar, and diagnostics modules.",
      "Add tests for reconnect after HMR/reload and detached PTY recovery.",
      "Add a visible current working directory chip for every terminal tab.",
      "Add command history search scoped per tab.",
      "Add copy-output and save-output actions with clear truncation behavior.",
      "Add keyboard shortcuts for new tab, close tab, next tab, and clear.",
      "Add mobile safe-area padding so terminal input does not collide with bottom controls.",
      "Add high-contrast terminal theme validation.",
      "Add a route smoke assertion that xterm rendered at least one terminal row.",
      "Add a diagnostic bundle for session id, shell, cwd, transport, and last close reason.",
      "Add idle timeout warnings before backend session reaping.",
      "Add a \"resume last terminal\" state when a PTY is still alive.",
      "Reduce inline explanatory text and rely on icons/tooltips for known terminal actions.",
      "Add a read-only mode for reviewing output without accidental input on mobile.",
    ],
  },
  {
    id: "jobs",
    label: "Jobs",
    route: "/jobs",
    match: (path) => path.startsWith('/jobs'),
    recommendations: [
      "Make the next scheduled job and last failed job the two strongest visual elements.",
      "Add clear grouping by automation owner: Hermes, Codex, workspace, and external.",
      "Add a failure-recovery CTA directly on failed job rows.",
      "Add \"last run duration\" and \"next run\" as aligned columns for scanability.",
      "Add a compact mobile card layout that hides low-priority metadata.",
      "Add filters for failed, stale, paused, and recently changed jobs.",
      "Add a no-op success state that respects automation contracts like silent or no reply.",
      "Extract job table, dialogs, filters, and action handlers from `jobs-screen.tsx`.",
      "Add tests for run recovery labels and scheduled retry text.",
      "Add optimistic action states for pause/resume/run now.",
      "Add a safe confirmation flow for disabling important jobs.",
      "Add diagnostics export for selected job, logs, schedule, owner, and last error.",
      "Add inline log tail expansion for failed jobs.",
      "Add \"affected pages\" or \"affected systems\" tags to jobs where known.",
      "Add a freshness warning when the job list source is stale.",
      "Add keyboard support for table navigation.",
      "Add saved views for \"daily checks\" and \"needs Tyler.\"",
      "Add a route smoke assertion for a failed or empty state fixture.",
      "Normalize job status colors with Dashboard severity colors.",
      "Add a \"what changed since last run\" summary when job metadata changes.",
    ],
  },
  {
    id: "tasks",
    label: "Tasks",
    route: "/tasks",
    match: (path) => path.startsWith('/tasks'),
    recommendations: [
      "Make \"Daily queue\" the default mental model and keep secondary analytics below it.",
      "Add a \"blocked by me\" lane that mirrors Dashboard wording.",
      "Add one-tap defer, delegate, and done actions optimized for mobile.",
      "Add stronger empty states for no tasks, no urgent tasks, and source unavailable.",
      "Add grouping by source: chat, meetings, phone capture, jobs, and manual.",
      "Add keyboard shortcuts for create, complete, defer, and focus next.",
      "Split `tasks-screen.tsx` into task query, filters, board/list, dialogs, and analytics.",
      "Move local task display selectors into pure functions with tests.",
      "Add drag-and-drop only where it improves repeated use; keep mobile actions tap-first.",
      "Add a \"today's promise\" pinned task that syncs to Dashboard and Phone.",
      "Add owner workload drill-down from the visible workload card.",
      "Add due-date risk badges that match Jobs and IT Ops severity language.",
      "Add batch triage mode for inbox-zero style cleanup.",
      "Add search and command palette integration for creating tasks from anywhere.",
      "Add diagnostic export for current filters, loaded tasks, and source freshness.",
      "Add route smoke coverage for task creation dialog open state.",
      "Add persisted view preferences through typed storage.",
      "Add mobile safe-area padding for bottom actions.",
      "Reduce first-viewport card count; prioritize tasks over analytics.",
      "Add integration tests for Phone capture to Tasks handoff.",
    ],
  },
  {
    id: "75-tracker",
    label: "75 Hard/Soft",
    route: "/75-tracker",
    match: (path) => path.startsWith('/75-tracker'),
    recommendations: [
      "Keep the page lightweight, but add a stronger \"remaining today\" primary action.",
      "Add a quick toggle mode that avoids scrolling on mobile.",
      "Add streak risk messaging when a required habit is close to missed.",
      "Add recovery notes for soft-mode misses so the page is not only binary.",
      "Add a daily check-in notification hook for Phone Cockpit.",
      "Add a weekly trend legend that does not require color alone.",
      "Add typed persistence for checked state, history, and custom template.",
      "Add unit tests for date rollover and localStorage migration.",
      "Add export to Tasks for any unfinished habit.",
      "Add a \"reset today\" confirmation to avoid accidental data loss.",
      "Add accessible labels for each habit checkbox and heatmap cell.",
      "Add a mobile compact summary: complete count, next habit, streak risk.",
      "Add a custom habit template manager instead of a single text field.",
      "Add per-habit notes for the user to record context.",
      "Add a dashboard widget integration using the same data source.",
      "Add a \"travel day\" or \"modified day\" setting for realistic daily usage.",
      "Add route smoke coverage for hard/soft mode switching.",
      "Add a small progress ring, but keep it secondary to the next action.",
      "Add cross-device persistence if this becomes daily-critical.",
      "Split helper functions out of the route once the page grows further.",
    ],
  },
  {
    id: "conductor",
    label: "Conductor",
    route: "/conductor",
    match: (path) => path.startsWith('/conductor'),
    recommendations: [
      "Add a real H1 or visually hidden page title for Conductor.",
      "Make \"Launch a mission\" visually dominant and keep advanced controls collapsed.",
      "Add a mission-readiness checklist before spawn: goal, cwd, model, tools, approvals.",
      "Add stronger distinction between portable prompt generation and live orchestrator spawn.",
      "Add recovery for saved mission draft and active mission at the top of the page.",
      "Split the 3,600-line screen and 1,700-line hook into mission form, stream, history, approvals, and artifacts.",
      "Move localStorage mission persistence into a typed store with versioning.",
      "Add tests for active mission restore, pause, steer, and stream failure.",
      "Add clear provenance for spawned files, commands, and agent outputs.",
      "Add a compact mobile launch flow with one textarea, model picker, and launch button.",
      "Add approval-state chips that match the rest of the workspace severity system.",
      "Add a \"copy portable plan\" confirmation showing what will be included.",
      "Add route-level diagnostics for mission id, session key, stream state, and last error.",
      "Add backpressure handling UI when stream output is delayed.",
      "Add a mission template search that shares patterns with Skills and MCP search.",
      "Add keyboard shortcuts for launch, stop, steer, and copy.",
      "Add a visible \"cwd locked\" indicator when mission scope is constrained.",
      "Add a post-mission summary that can create Tasks and update Dashboard.",
      "Add visual smoke coverage for an active mission fixture.",
      "Reduce nested cards in the first viewport to improve operator scan speed.",
    ],
  },
  {
    id: "operations",
    label: "Operations",
    route: "/operations",
    match: (path) => path.startsWith('/operations'),
    recommendations: [
      "Clarify whether Operations manages agents, profiles, jobs, or all three in the first viewport.",
      "Add a visible health summary for each active agent.",
      "Add one primary action: create agent, resume agent, or inspect failing agent based on state.",
      "Replace route-level reload fallback with shared route recovery UI.",
      "Add filters for active, idle, failed, and needs Tyler.",
      "Add compact mobile cards with status, owner, and next action only.",
      "Move agent metadata localStorage into typed persistence.",
      "Split operation screen components into roster, detail, chat, jobs, and settings.",
      "Add tests for profile-backed agent creation and delete safeguards.",
      "Add a clear path from Operations to Profiles when profile config is the blocker.",
      "Add output previews that link to Jobs or Chat where the work originated.",
      "Add \"last useful output\" and \"last heartbeat\" to each agent card.",
      "Add a diagnostic export for selected agent and associated jobs.",
      "Add inline empty states for no agents and missing default profile.",
      "Add keyboard navigation across agent roster and detail panes.",
      "Add stronger visual distinction between human-owned and autonomous operations.",
      "Add action audit trail for changes to agent settings.",
      "Add route smoke coverage for opening the new agent modal.",
      "Normalize status colors with Swarm and Conductor.",
      "Keep the page operational and dense, but reduce decorative borders around repeated rows.",
    ],
  },
  {
    id: "ops-intelligence",
    label: "Ops Intelligence",
    route: "/ops-intelligence",
    match: (path) => path.startsWith('/ops-intelligence'),
    recommendations: [
      "Promote the top three operational risks above the long report sections.",
      "Add timestamps and source names to every insight block.",
      "Make \"Changes Since Last Update\" collapsible once reviewed.",
      "Add links from each recommendation to the page or job that can fix it.",
      "Add a confidence label: observed, inferred, stale, or needs live verification.",
      "Add a mobile \"at a glance\" mode with risks, blockers, and next action only.",
      "Split report rendering, data loading, filters, and action generation modules.",
      "Add tests for stale source handling and empty report rendering.",
      "Add an export format that can become a weekly operations note.",
      "Add diffing between current and previous ops intelligence snapshots.",
      "Add severity colors consistent with Dashboard and Jobs.",
      "Add a \"mark reviewed\" flow that logs review time and hides repeated findings.",
      "Add a route diagnostic bundle for report source, generated time, and failed sections.",
      "Add skeleton sections so loading does not look like missing content.",
      "Add search across recommendations and source evidence.",
      "Add a compact table of \"owner / system / risk / action\".",
      "Add an action queue handoff into Tasks.",
      "Add visual smoke coverage for stale and healthy data fixtures.",
      "Avoid long prose blocks when a metric/table would be easier to scan.",
      "Add a \"what changed today\" chip to the shell/sidebar.",
    ],
  },
  {
    id: "swarm",
    label: "Swarm",
    route: "/swarm",
    match: (path) => path === '/swarm' || path.startsWith('/swarm2'),
    recommendations: [
      "Add a clearer distinction between swarm overview, worker controls, and live queue.",
      "Add a real-time health strip that stays visible while scrolling.",
      "Replace route-level reload fallback with shared recovery UI.",
      "Add \"needs Tyler\" as a first-class swarm state.",
      "Add a mobile compact queue that shows only blocked, running, and next worker.",
      "Split `swarm2-screen.tsx` into overview, workers, queue, artifacts, memory, and reports modules.",
      "Add tests for recommended worker selection and surface distinction.",
      "Add a per-worker diagnostic bundle with tools, cwd, task, and last error.",
      "Add visual status consistency with Operations and Conductor.",
      "Add a safe stop/restart confirmation for active workers.",
      "Add a route smoke assertion for queue and worker panel visibility.",
      "Add event-log virtualization for long swarm sessions.",
      "Add a \"promote to task\" action from swarm output.",
      "Add a \"resume last swarm\" button when runtime state exists.",
      "Add search across artifacts and worker messages.",
      "Add a low-noise default view that hides advanced wiring until needed.",
      "Add keyboard shortcuts for focus worker, stop, restart, and open artifact.",
      "Add latency and heartbeat indicators per worker.",
      "Add stronger empty state when no swarm runtime is configured.",
      "Reduce first-viewport visual competition between cards and node/wire graphics.",
    ],
  },
  {
    id: "memory",
    label: "Memory",
    route: "/memory",
    match: (path) => path.startsWith('/memory'),
    recommendations: [
      "Add a real H1 or visually hidden title for Memory.",
      "Make search the dominant first action.",
      "Add source filters: Codex memory, Hermes memory, rollout summaries, skills, and workspace docs.",
      "Add result provenance and last-updated metadata to every memory hit.",
      "Add a \"use in current task\" action that copies or injects selected memory context.",
      "Add stale-memory warnings when a note may drift.",
      "Split browser screen into search, tree, preview, metadata, and actions.",
      "Add tests for search empty state, read failure, and stale metadata display.",
      "Add keyboard navigation for result list and preview.",
      "Add mobile search-first layout with filters in a bottom sheet.",
      "Add a diagnostic export for search query, selected source, and API status.",
      "Add highlighting of matched text snippets.",
      "Add a \"recently used by Codex\" section.",
      "Add safe edit boundaries if writing memory notes becomes supported.",
      "Add visual distinction between durable memory and temporary transcript data.",
      "Add route smoke coverage for a search result fixture.",
      "Add pagination or virtualization for large memory folders.",
      "Add cross-linking to Skills when memory references skill behavior.",
      "Add a \"verify live\" reminder for drift-prone facts.",
      "Keep the page utilitarian; avoid card-heavy decoration around search results.",
    ],
  },
  {
    id: "skills",
    label: "Skills",
    route: "/skills",
    match: (path) => path.startsWith('/skills'),
    recommendations: [
      "Make installed, available, and recently used skills visually distinct.",
      "Add a first-viewport \"recommended for current task\" section.",
      "Add search result snippets that show why a skill matched.",
      "Add clear install/update/remove risk labels.",
      "Add route links from Skills to MCP when a skill requires a tool/server.",
      "Split `skills-screen.tsx` into installed list, marketplace search, usage, and mutation hooks.",
      "Add tests for install, toggle, uninstall, and hub search failure states.",
      "Add optimistic mutation states with rollback on failure.",
      "Add mobile filter chips for installed, update available, and disabled.",
      "Add a \"last used\" sort mode.",
      "Add a diagnostics export for skill path, source, enabled state, and last error.",
      "Add safer confirmation copy for uninstalling local skills.",
      "Add a skill detail drawer with instructions, files, and related memories.",
      "Add warning when a skill is duplicated across multiple roots.",
      "Add visual smoke coverage for marketplace install confirmation.",
      "Add keyboard navigation and command palette integration.",
      "Normalize empty/error states with MCP and Profiles.",
      "Add a \"pin favorite skills\" section for daily Tyler workflows.",
      "Add a lint check for skill metadata health if local skills are edited here.",
      "Reduce repeated card outlines in large result lists.",
    ],
  },
  {
    id: "mcp",
    label: "MCP Servers",
    route: "/mcp",
    match: (path) => path.startsWith('/mcp'),
    recommendations: [
      "Put unhealthy servers and missing auth at the top of the page.",
      "Add a capability matrix by server: tools, resources, prompts, auth, and risk.",
      "Add a one-click test flow that shows request, response status, and redacted error.",
      "Add clearer separation between installed servers, hub sources, presets, and logs.",
      "Add mobile cards with health, primary action, and last error only.",
      "Split server cards, dialogs, sources, presets, and OAuth hooks more explicitly.",
      "Add tests for OAuth, placeholder detection, source manager, and preset application paths.",
      "Add a diagnostic export for selected server configuration with secrets redacted.",
      "Add route links from MCP to Skills where a skill depends on a server.",
      "Add warnings for placeholder values before a user tries to start a server.",
      "Add a \"recently failed\" filter.",
      "Add source provenance for marketplace/hub server definitions.",
      "Add safe restart confirmation for running servers.",
      "Add inline log snippets for failed servers.",
      "Add keyboard navigation through server cards.",
      "Add visual smoke coverage for logs drawer open state.",
      "Normalize status colors with Settings provider health.",
      "Add \"last successful tool call\" metadata where available.",
      "Add a guided setup for common servers.",
      "Keep the screen dense, but reduce modal depth for simple edits.",
    ],
  },
  {
    id: "profiles",
    label: "Profiles",
    route: "/profiles",
    match: (path) => path.startsWith('/profiles'),
    recommendations: [
      "Clarify whether profiles affect chat, agents, tools, or all workspace behavior in the first viewport.",
      "Add an active-profile banner with quick switch.",
      "Add a profile diff view before saving edits.",
      "Add \"used by\" references: Chat, Operations, Conductor, and Jobs.",
      "Add duplicate-profile detection based on config similarity.",
      "Split `profiles-screen.tsx` into list, editor, validation, and API hooks.",
      "Add tests for create, rename, update, activate, and delete failure states.",
      "Add mobile profile cards with active state and top three capabilities.",
      "Add import/export for profiles with secret redaction.",
      "Add validation badges for model, provider, tools, and routing.",
      "Add a safe delete flow that blocks deleting active/default profiles.",
      "Add last-used and last-edited metadata.",
      "Add route links to Settings provider configuration when validation fails.",
      "Add command palette support for switching profiles.",
      "Add visual smoke coverage for profile editor open state.",
      "Add optimistic activate behavior with rollback if the API fails.",
      "Add a \"make a copy\" action for experimentation.",
      "Add a profile health summary that mirrors Settings health.",
      "Add keyboard navigation between list and editor.",
      "Reduce form density by grouping advanced settings behind sections.",
    ],
  },
  {
    id: "meetings",
    label: "Meetings",
    route: "/meetings",
    match: (path) => path.startsWith('/meetings'),
    recommendations: [
      "Make \"Today and next\" the clear top priority on desktop and mobile.",
      "Add a meeting-prep CTA when a meeting is within a configurable window.",
      "Add \"needs follow-up\" extraction into Tasks.",
      "Add source freshness and calendar sync status near the title.",
      "Add attendee and owner chips that are scannable without opening detail.",
      "Split the 2,100-line screen into today, records, detail, actions, and trend modules.",
      "Add tests for meeting detail load, action failure, and follow-up creation.",
      "Add mobile agenda mode with only next meeting, prep, and open follow-ups.",
      "Add \"copy meeting brief\" with redaction controls.",
      "Add search by attendee, title, and action item.",
      "Add filters for today, this week, missing notes, and needs follow-up.",
      "Add skeletons for calendar loading.",
      "Add route diagnostics for sync source, last refresh, and failed actions.",
      "Add visual smoke coverage for meeting detail selected state.",
      "Add keyboard shortcuts for next meeting and create follow-up.",
      "Add a clear empty state for no meetings today.",
      "Add trend interpretation for the two-week load chart.",
      "Add \"join\" or location handling if present in source data.",
      "Normalize meeting severity with Dashboard daily-loop language.",
      "Reduce repeated card borders in recent meeting records.",
    ],
  },
  {
    id: "presence",
    label: "Presence",
    route: "/presence",
    match: (path) => path.startsWith('/presence'),
    recommendations: [
      "Put current Tyler availability and last sync status at the top.",
      "Add a clear distinction between Teams status, manual override, and inferred workspace status.",
      "Add source freshness beside each presence source.",
      "Add one primary sync action when data is stale.",
      "Add a compact mobile glance card with status, next event, and sync.",
      "Split presence screen into status summary, sync diagnostics, manual actions, and history.",
      "Add tests for sync failure, stale status, and manual override.",
      "Add route diagnostics for Teams auth, last sync, and source errors.",
      "Add status history sparklines only if they answer a workflow question.",
      "Add \"do not disturb until\" quick presets.",
      "Add integration with Phone Cockpit so daily glance uses the same presence status.",
      "Add accessible status colors with text labels.",
      "Add visual smoke coverage for stale sync state.",
      "Add keyboard shortcuts for sync and set focus state.",
      "Add clear error copy when Graph or Teams auth is unavailable.",
      "Add \"copy status\" for sharing availability.",
      "Add filtering for people/systems if presence expands.",
      "Add optimistic UI for manual sync actions.",
      "Add persistent user preference for default presence mode.",
      "Keep diagnostics available but secondary to current availability.",
    ],
  },
  {
    id: "it-ops",
    label: "IT Ops / ConnectWise",
    route: "/it-ops",
    match: (path) => path.startsWith('/it-ops'),
    recommendations: [
      "Make SLA risk and approval blockers the first row.",
      "Add direct links from ticket cards to the exact ConnectWise object when available.",
      "Add status labels for native ConnectWise approvals versus workspace-derived insights.",
      "Add a \"needs Tyler approval\" filter.",
      "Add source freshness and last sync near the page title.",
      "Split IT Ops screen into briefing, tickets, approvals, recurring issues, and actions.",
      "Add tests for stale data, no tickets, and approval risk rendering.",
      "Add mobile glance mode: urgent tickets, approvals, next action.",
      "Add a diagnostic export for ticket source, sync status, and failed sections.",
      "Add \"copy client update\" and \"copy internal brief\" actions with clear templates.",
      "Add recurring-issue grouping that links related tickets.",
      "Add severity colors aligned with Dashboard and Jobs.",
      "Add visual smoke coverage for ticket detail expanded state.",
      "Add empty states that distinguish no tickets from failed ConnectWise sync.",
      "Add keyboard navigation for ticket list.",
      "Add owner and due-date chips that are aligned for scanning.",
      "Add a clear native-PSA boundary note in diagnostics, not as visible page clutter.",
      "Add a \"last touched\" marker for tickets recently updated by Tyler.",
      "Add Tasks handoff for follow-ups that are not native PSA actions.",
      "Reduce prose in the briefing when a table or queue would be faster to scan.",
    ],
  },
  {
    id: "barry",
    label: "Barry",
    route: "/barry",
    match: (path) => path.startsWith('/barry'),
    recommendations: [
      "Clarify Barry's current role in the first viewport: meetings, assistant, or operations contact.",
      "Add the next Barry-related action as the primary CTA.",
      "Add a meeting summary card only when there is meeting data.",
      "Add source freshness near the title.",
      "Add a compact mobile card for next meeting, last note, and follow-up.",
      "Split Barry screen into summary, meetings, actions, and data hooks.",
      "Add tests for load failure, empty meetings, and action failure.",
      "Add route diagnostics for Barry data source and last API error.",
      "Add \"copy Barry brief\" action.",
      "Add Tasks handoff for Barry follow-ups.",
      "Add filters for upcoming, recent, and needs follow-up.",
      "Add skeletons for meeting/action loading.",
      "Add visual smoke coverage for a non-empty meeting state.",
      "Add consistent severity/freshness chips with Meetings.",
      "Add command palette action to open Barry.",
      "Add keyboard support for selecting a meeting.",
      "Add clearer empty state when Barry has no current work.",
      "Add a cross-link to Meetings when the content is primarily calendar-driven.",
      "Add a compact \"last interaction\" timestamp.",
      "Reduce generic cards until the page has enough Barry-specific data to justify them.",
    ],
  },
  {
    id: "settings",
    label: "Settings",
    route: "/settings",
    match: (path) => path.startsWith('/settings'),
    recommendations: [
      "Move the update toast away from the settings search and tab chips.",
      "Improve contrast on the gray health cards in dark mode; they look detached from the rest of the theme.",
      "Make \"Provider missing\" the primary recovery path when it is the highest-risk setting.",
      "Add a settings search result count and matched-section highlights.",
      "Add \"unsaved / autosaved / failed to save\" state near the active section.",
      "Split the 3,400-line settings route into sections, health, validation, persistence, and export modules.",
      "Add tests for each validation state, export bundle, reset section, and setup wizard.",
      "Add route links from health chips directly to the problematic controls.",
      "Add mobile grouping that shows only Core, AI, Voice, Look, and Alerts by default.",
      "Add a \"copy safe diagnostics\" button beside export profile.",
      "Add profile import validation before writing settings.",
      "Add a provider setup wizard that can verify credentials without exposing secrets.",
      "Add stronger visual distinction between workspace settings and chat-only settings.",
      "Add command palette actions for common settings pages.",
      "Add keyboard navigation for section tabs.",
      "Add a sticky section nav on desktop when scrolling deep settings.",
      "Add an accessibility pass for chip groups and section tabs.",
      "Add settings schema versioning and migration reporting.",
      "Add visual smoke coverage for setup wizard open state.",
      "Reduce repeated rounded panels and use fewer, stronger section boundaries.",
    ],
  },
]

export function findWorkspaceImprovementPage(pathname: string) {
  return (
    WORKSPACE_IMPROVEMENT_PAGES.find((page) => page.match(pathname)) ?? null
  )
}

export function countWorkspaceRecommendations() {
  return WORKSPACE_IMPROVEMENT_PAGES.reduce(
    (count, page) => count + page.recommendations.length,
    0,
  )
}
